from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
import httpx

from .config import get_settings
from .schemas import ChatRequest, RoleName, TranscriptionResponse, UploadItem, UploadResponse
from .service import build_answer, get_dashboard


settings = get_settings()
app = FastAPI(title=settings.app_name)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
async def health() -> dict:
    return {"ok": True, "app": settings.app_name}


@app.get("/api/dashboard/{role}")
async def dashboard(role: RoleName):
    return get_dashboard(role)


@app.post("/api/chat")
async def chat(request: ChatRequest):
    return await build_answer(request.question, request.role)


@app.post("/api/upload")
async def upload_files(files: list[UploadFile] = File(...)):
    accepted_suffixes = {".pdf", ".doc", ".docx", ".png", ".jpg", ".jpeg", ".gif", ".webp"}
    normalized_files: list[UploadItem] = []

    for uploaded in files:
        filename = uploaded.filename or "untitled"
        suffix = "." + filename.split(".")[-1].lower() if "." in filename else ""
        if suffix not in accepted_suffixes:
            raise HTTPException(status_code=400, detail=f"Unsupported file type: {filename}")
        content = await uploaded.read()
        if suffix == ".pdf":
            category = "pdf"
        elif suffix in {".doc", ".docx"}:
            category = "word"
        elif suffix in {".png", ".jpg", ".jpeg", ".gif", ".webp"}:
            category = "image"
        else:
            category = "other"
        normalized_files.append(
            UploadItem(
                name=filename,
                media_type=uploaded.content_type or "application/octet-stream",
                size_bytes=len(content),
                category=category,
            )
        )
    return UploadResponse(files=normalized_files)


@app.post("/api/transcribe")
async def transcribe_audio(file: UploadFile = File(...)):
    if not settings.elevenlabs_api_key:
        raise HTTPException(
            status_code=503,
            detail=(
                "ElevenLabs transcription is not configured. "
                "Set CAREPROOF_ELEVENLABS_API_KEY to enable audio question input."
            ),
        )

    audio_bytes = await file.read()
    if not audio_bytes:
        raise HTTPException(status_code=400, detail="Empty audio file.")

    files = {
        "file": (file.filename or "question.webm", audio_bytes, file.content_type or "audio/webm")
    }
    data = {
        "model_id": settings.elevenlabs_stt_model,
        "diarize": "false",
        "tag_audio_events": "false",
    }
    headers = {"xi-api-key": settings.elevenlabs_api_key}

    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            "https://api.elevenlabs.io/v1/speech-to-text",
            headers=headers,
            data=data,
            files=files,
        )
    if response.status_code >= 400:
        raise HTTPException(status_code=502, detail=f"ElevenLabs transcription failed: {response.text}")

    payload = response.json()
    return TranscriptionResponse(
        text=payload.get("text", ""),
        provider="ElevenLabs",
        model=settings.elevenlabs_stt_model,
        note="Speech-to-text generated by ElevenLabs.",
    )
